# -*- coding: utf-8 -*-
"""d_a_p_cars.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zF4i-vPPGKifQWdYfzmzLXoV_XOK6SAI
"""

import pandas as pd

data=pd.read_csv('cars_dataset.csv')

"""data cleaning

find any null values and data replace them with 0 values

"""

data.head(5)

data.shape

data.isnull().sum()

data['Cylinders'].fillna(data['Cylinders'].mean(),inplace=True)

"""valus counts:
check what are the different types of make are there in dataset
"""

data.head(2)

data['Make'].value_counts()

"""filtering"""

data[data['Origin']=='Asia']

data[data['Origin'].isin(['Asia' , 'Europe'])]

"""removing unwanted rows(instructions)where weight is above 4000

"""

data[data['Weight']>4000] #show above 4000

data[~(data['Weight']>4000)]

"""increase all the values of column "mpg-highway " column by 3"""

data['MPG_Highway']=data['MPG_Highway'].apply(lambda x:x+3)

data